import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";

const Playfair = Playfair_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Karepal",
  description: "Generated by create next appTransforming care giving through data driven AI tools",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Playfair.className}>{children}</body>
    </html>
  );
}
